# Generated by Django 5.0.7 on 2024-08-01 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название уровня')),
                ('order', models.IntegerField(default=0, unique=True, verbose_name='Порядковый номер уровня')),
            ],
            options={
                'verbose_name': ('Уровень',),
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название приза')),
            ],
            options={
                'verbose_name': ('Приз',),
                'verbose_name_plural': 'Призы',
            },
        ),
        migrations.CreateModel(
            name='PlayerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.DateField(verbose_name='Момент прохождения уровня')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус прохождения')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Количество очков')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.level')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.prize')),
            ],
            options={
                'verbose_name': ('Приз игрока',),
                'verbose_name_plural': 'Призы игрока',
            },
        ),
        migrations.CreateModel(
            name='LevelPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.level')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.prize')),
            ],
            options={
                'verbose_name': ('Приз за уровень',),
                'verbose_name_plural': 'Призы за уровень',
            },
        ),
    ]
